# settings.yaml

---

default_wall: Shower Right

wall_settings:
    Sink:
        plans: {}
    Stove:
        plans: {}
    Dining:
        plans: {}
    Shower Back:
        plans: {}
    Shower Left:
        plans: {}
    Shower Right:
        default_plan: stacked
        plans:
            stacked:
                grout_gap: 1/4
                grout_color: orange
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                layout:
                    type: stacked
                    tile: 6x12
            stepped:
                grout_gap: 1/4
                grout_color: orange
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                layout:
                    type: stepped
                    tile: 6x12
                    percent_offset: 1/3
            stepped_rev:
                grout_gap: 1/4
                grout_color: orange
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                layout:
                    type: stepped
                    tile: 6x12
                    percent_offset: -1/3
            hopscotch_right:
                grout_gap: 1/4
                grout_color: orange
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                layout:
                    type: hopscotch
                    tile_a: 6x12
                    tile_b: 8" square white
                    right: true
            hopscotch_left:
                grout_gap: 1/4
                grout_color: orange
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                layout:
                    type: hopscotch
                    tile_a: 6x12
                    tile_b: 8" square white
                    right: false
            herringbone_right:
                grout_gap: 1/4
                grout_color: orange
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                layout:
                    type: herringbone
                    tile: 6x12
                    right: true
            herringbone_left:
                grout_gap: 1/4
                grout_color: orange
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                layout:
                    type: herringbone
                    tile: 6x12
                    right: false
