# settings.yaml

---
default_wall: Test Wall
#default_wall: Master Back
wall_settings:
    Dining:
        plans: {}
    Test Wall:
        default_plan: hopscotch_right
        plans:

            stacked:
                alignment:
                    angle: -45
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    type: stepped
                    tile: 8" square white
            stacked_image:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    type: stepped
                    tile: test_image

            stepped:
                alignment:
                    angle: -45
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    type: stepped
                    tile: 6x12
                    percent_offset: 1/3
            stepped_rev:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    type: stepped
                    tile: 6x12
                    percent_offset: -1/3

            star_cross_white:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    type: checkerboard
                    tile_a: cross-white
                    tile_b: star-white

            star_cross_white_cross:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    type: checkerboard
                    tile_a: cross-white
                    tile_b: star-cotto

            star_cross_white_star:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    type: checkerboard
                    tile_a: cross-cotto
                    tile_b: star-white

            hopscotch_left:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    type: hopscotch
                    tile_a: 4x12
                    tile_b: 8" square white
                    right: false
            hopscotch_right:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    type: hopscotch
                    tile_a: 4x12
                    tile_b: 8" square white
                    right: true

            herringbone_left:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    type: herringbone
                    tile: 6x12
                    right: false
            herringbone_right:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    type: herringbone
                    tile: 6x12
                    right: true

            box:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    type: box
                    tile: 8" square white
                    num_x: 4
                    num_y: 3
                    start: [5, 15]

            border:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    type: border
                    tile: 8" square white
                    num_x: 5
                    num_y: 4
                    start_x: 5
                    start_y: 15

            flower:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    type: flower
                    tile: test_image

            hex:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    type: stepped
                    tile: hex
                    percent_offset: 1/2

            picket:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    type: stepped
                    percent_offset: 1/2
                    tile: picket

    Sink:
        plans:
            hex:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/8
                layout:
                    type: stepped
                    tile: hex
                    percent_offset: 1/2
            picket:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/8
                layout:
                    type: stepped
                    tile: picket
                    percent_offset: 1/2
            picket_tilt:
                alignment:
                    angle: 16.9
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/8
                layout:
                    type: stepped
                    tile: picket
                    percent_offset: 1/2
            star_+:
                alignment:
                    angle: 45
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    type: checkerboard
                    tile_a: cross-white
                    tile_b: star-white
            star_X:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    type: checkerboard
                    tile_a: cross-white
                    tile_b: star-white
    Stove:
        plans:
            hex:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/8
                layout:
                    type: stepped
                    tile: hex
                    percent_offset: 1/2
            picket:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/8
                layout:
                    type: stepped
                    tile: picket
                    percent_offset: 1/2
            picket_tilt:
                alignment:
                    angle: 16.9
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/8
                layout:
                    type: stepped
                    tile: picket
                    percent_offset: 1/2
            star_+:
                alignment:
                    angle: 45
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    type: checkerboard
                    tile_a: cross-white
                    tile_b: star-white
            star_X:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    type: checkerboard
                    tile_a: cross-white
                    tile_b: star-white
    Guest Bath:
        plans: {}
    Master Left:
        default_plan: star_X
        plans:
            hex:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/8
                layout:
                    type: stepped
                    tile: hex
                    percent_offset: 1/2
            picket:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/8
                layout:
                    type: stepped
                    tile: picket
                    percent_offset: 1/2
            picket_tilt:
                alignment:
                    angle: 16.9
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/8
                layout:
                    type: stepped
                    tile: picket
                    percent_offset: 1/2
            star_+:
                alignment:
                    angle: 45
                    x_offset: 2.3/4
                    y_offset: -1.3/4
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    type: checkerboard
                    tile_a: cross-white
                    tile_b: star-white
            star_X:
                alignment:
                    angle: 0
                    x_offset: 2.3/4
                    y_offset: -1.3/4
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    type: checkerboard
                    tile_a: cross-white
                    tile_b: star-white
    Master Right:
        default_plan: star_X
        plans:
            hex:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/8
                layout:
                    type: stepped
                    tile: hex
                    percent_offset: 1/2
            picket:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/8
                layout:
                    type: stepped
                    tile: picket
                    percent_offset: 1/2
            picket_tilt:
                alignment:
                    angle: 16.9
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/8
                layout:
                    type: stepped
                    tile: picket
                    percent_offset: 1/2
            star_+:
                alignment:
                    angle: 45
                    x_offset: 3/4
                    y_offset: 5
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    tile_a: cross-white
                    tile_b: star-white
                    type: checkerboard
            star_X:
                alignment:
                    angle: 0
                    x_offset: 3/4
                    y_offset: 5
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    tile_a: cross-white
                    tile_b: star-white
                    type: checkerboard
    Master Back:
        default_plan: star_+
        #default_plan: star_X
        plans:
            hex:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/8
                layout:
                    type: stepped
                    tile: hex
                    percent_offset: 1/2
            picket:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/8
                layout:
                    type: stepped
                    tile: picket
                    percent_offset: 1/2
            picket_tilt:
                alignment:
                    angle: 16.9
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/8
                layout:
                    type: stepped
                    tile: picket
                    percent_offset: 1/2
            star_+:
                alignment:
                    angle: 45
                    x_offset: -3.9/16
                    y_offset: 1/4
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    type: checkerboard
                    tile_a: cross-white
                    tile_b: star-white

            star_X:
                alignment:
                    angle: 0
                    x_offset: -3.9/16
                    y_offset: 1/4
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    type: checkerboard
                    tile_a: cross-white
                    tile_b: star-white

            star_X-taupe:
                alignment:
                    angle: 0
                    x_offset: -3.9/16
                    y_offset: 1/4
                grout_color: darkorange
                grout_gap: 1/4
                layout:
                    type: checkerboard
                    tile_a: cross-taupe
                    tile_b: star-taupe

            star_X-cotto:
                alignment:
                    angle: 0
                    x_offset: -3.9/16
                    y_offset: 1/4
                grout_color: darkorange
                grout_gap: 1/4
                layout:
                    type: checkerboard
                    tile_a: cross-cotto
                    tile_b: star-cotto

            star_X-Morocco-6:
                alignment:
                    angle: 0
                    x_offset: -3.9/16
                    y_offset: 1/4
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    type: sequence
                    steps:
                        - type: checkerboard
                          tile_a: cross-white
                          tile_b: star-white
                        - type: box
                          tile: Morocco-6
                          num_x: 6
                          num_y: 5
                          start: [8.1/4, 45.1/4]

            star_X-Nube Verde-6:
                alignment:
                    angle: 0
                    x_offset: -3.9/16
                    y_offset: 1/4
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    type: sequence
                    steps:
                        - type: checkerboard
                          tile_a: cross-white
                          tile_b: star-white
                        - type: box
                          tile: Nube Verde-6
                          num_x: 6
                          num_y: 5
                          start: [8.1/4, 45.1/4]

            star_X-Nube Verde-4:
                alignment:
                    angle: 0
                    x_offset: -3.9/16
                    y_offset: 1/4
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    type: sequence
                    steps:
                        - type: checkerboard
                          tile_a: cross-white
                          tile_b: star-white
                        - type: box
                          tile: Nube Verde-4
                          num_x: 8
                          num_y: 6
                          start: [9.3/4, 48.1/4]

            star_X-Estrella de Fuego-6:
                alignment:
                    angle: 0
                    x_offset: -3.9/16
                    y_offset: 1/4
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    type: sequence
                    steps:
                        - type: checkerboard
                          tile_a: cross-white
                          tile_b: star-white
                        - type: box
                          tile: Estrella de Fuego-6
                          num_x: 6
                          num_y: 5
                          start: [8.1/4, 45.1/4]

            star_X-Arabesque Azul-6-close:
                alignment:
                    angle: 0
                    x_offset: -3.9/16
                    y_offset: 1/4
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    type: sequence
                    steps:
                        - type: checkerboard
                          tile_a: cross-white
                          tile_b: star-white
                        - type: border
                          tile: Arabesque Azul-6
                          num_x: 6
                          num_y: 5
                          start_x: 8.1/4
                          start_y: 45.1/4

            star_X-Arabesque Azul-6-gap:
                alignment:
                    angle: 0
                    x_offset: -3.9/16
                    y_offset: 1/4
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    type: sequence
                    steps:
                        - type: checkerboard
                          tile_a: cross-white
                          tile_b: star-white
                        - type: border
                          tile: Arabesque Azul-6
                          num_x: 7
                          num_y: 6
                          start_x: 5.1/4
                          start_y: 42.1/4

