# settings.yaml

---
default_wall: Shower Right
wall_settings:
    Dining:
        plans: {}
    Shower Back:
        plans: {}
    Shower Left:
        plans: {}
    Shower Right:
        default_plan: stepped
        plans:
            herringbone_left:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    right: false
                    tile: 6x12
                    type: herringbone
            herringbone_right:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    right: true
                    tile: 6x12
                    type: herringbone
            hex:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    percent_offset: 1/2
                    tile: hex
                    type: stepped
            hopscotch_left:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    right: false
                    tile_a: 6x12
                    tile_b: 8" square white
                    type: hopscotch
            hopscotch_right:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    right: true
                    tile_a: 6x12
                    tile_b: 8" square white
                    type: hopscotch
            picket:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    percent_offset: 1/2
                    tile: picket
                    type: stepped
            stacked:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    tile: 8" square white
                    type: stacked
            stacked_image:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    tile: test_image
                    type: stacked

            star_cross:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    tile_a: cross
                    tile_b: star
                    type: checkerboard
            stepped:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    percent_offset: 1/3
                    tile: 6x12
                    type: stepped
            stepped_rev:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    percent_offset: -1/3
                    tile: 6x12
                    type: stepped
    Sink:
        plans:
            hex:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/8
                layout:
                    percent_offset: 1/2
                    tile: hex
                    type: stepped
            picket:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/8
                layout:
                    percent_offset: 1/2
                    tile: picket
                    type: stepped
            picket_tilt:
                alignment:
                    angle: 16.9
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/8
                layout:
                    percent_offset: 1/2
                    tile: picket
                    type: stepped
            star_+:
                alignment:
                    angle: 45
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    tile_a: cross
                    tile_b: star
                    type: checkerboard
            star_X:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    tile_a: cross
                    tile_b: star
                    type: checkerboard
    Stove:
        plans:
            hex:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/8
                layout:
                    percent_offset: 1/2
                    tile: hex
                    type: stepped
            picket:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/8
                layout:
                    percent_offset: 1/2
                    tile: picket
                    type: stepped
            picket_tilt:
                alignment:
                    angle: 16.9
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/8
                layout:
                    percent_offset: 1/2
                    tile: picket
                    type: stepped
            star_+:
                alignment:
                    angle: 45
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    tile_a: cross
                    tile_b: star
                    type: checkerboard
            star_X:
                alignment:
                    angle: 0
                    x_offset: 0
                    y_offset: 0
                grout_color: acorn
                grout_gap: 1/4
                layout:
                    tile_a: cross
                    tile_b: star
                    type: checkerboard
